apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-sidplaceholder
  namespace: rbac-sidplaceholder
  labels:
    owner: "sidplaceholder"
data:
  owner: "sidplaceholder"
  studentName: "Christian Onwuanaku"
  project: "CLO835 Project 11"
  message: "RBAC personas and break-glass demonstration"
