apiVersion: v1
kind: Secret
metadata:
  name: db-creds-sidplaceholder
  namespace: rbac-sidplaceholder
  labels:
    owner: "sidplaceholder"
type: Opaque
stringData:
  username: "demo-user"
  password: "dummy-project-password"
