apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sidplaceholder
  namespace: rbac-sidplaceholder
  labels:
    owner: "sidplaceholder"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-sidplaceholder
  namespace: rbac-sidplaceholder
  labels:
    owner: "sidplaceholder"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-sidplaceholder
  namespace: rbac-sidplaceholder
  labels:
    owner: "sidplaceholder"
