apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-role-sidplaceholder
  namespace: rbac-sidplaceholder
  labels:
    owner: "sidplaceholder"
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-binding-sidplaceholder
  namespace: rbac-sidplaceholder
  labels:
    owner: "sidplaceholder"
subjects:
  - kind: ServiceAccount
    name: ci-sidplaceholder
    namespace: rbac-sidplaceholder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-role-sidplaceholder
